## Data Structure :

In [ ]:
import numpy as np
# data of restaurant sales :

data = np.array([
    [1, 1200,1400,4322,4500,4599],#nanskar
    [2, 1144,4585,5265,4852,4585],#pappe
    [3, 7852,4586,9625,4852,3571],#cholewale
    [4, 7864,8569,4500,8035,2345],#dosaram
    [5, 7896,8522,7931,8016,1495],#hub
])

print("shape of array", data.shape)
print("Required Value:\n", data[0:3])
#this means all the row and coloumn starting from index 1 till end
print("Required Value in fancy way:\n", data[:,1:])

# <-------------numpy logic------------------->
sales_per_year= np.sum(data[:,1:],axis=0)
print("Sales per year:\n", sales_per_year)


sales_per_year= np.sum(data,axis=1)
print("Sales Of Each restaurant:\n", sales_per_year)

# <------------python logic------------------->
# total sales 
from functools import reduce 
sales_nanskar= data[1,1:]
total_sales= reduce(lambda x,y:x+y,sales_nanskar)
print("total_sales nanskar " , total_sales)



shape of array (5, 6)
Required Value:
 [[   1 1200 1400 4322 4500 4599]
 [   2 1144 4585 5265 4852 4585]
 [   3 7852 4586 9625 4852 3571]]
Required Value in fancy way:
 [[1200 1400 4322 4500 4599]
 [1144 4585 5265 4852 4585]
 [7852 4586 9625 4852 3571]
 [7864 8569 4500 8035 2345]
 [7896 8522 7931 8016 1495]]
Sales per year: [25956 27662 31643 30255 16595]
Sales per year: [16022 20433 30489 31317 33865]
total_sales nanskar  20431
