## Day 01 numpy
it is famous for performing better operations on simmilar datatypes

In [46]:
import numpy as np

## 1D Array :

In [47]:
arr_1D= np.array([1,2,3,4,5,6])
print(arr_1D)

[1 2 3 4 5 6]


## 2D Array: 

In [48]:
arr_2D = np.array([[1,2,3], [4,5,6]])
print(arr_2D)

[[1 2 3]
 [4 5 6]]


## arrays multiplication in array 

In [49]:
# multlipication in array
#list multiply the number itself twice
list = [1, 2, 3, 4, 5, 6]
print(list * 2)

#numpy multiplies the array by scaler 2 
list2 = np.array([1, 2, 3, 4, 5, 6])

print(list2 * 2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 2  4  6  8 10 12]


## arays from scratch 

In [50]:
#zeroes array
zeros = np.zeros((3,2)) #3,3 is number of elements in array , 2 is numer of arrays simply matrix that has 3 rows and 2 coloumns
print("Zeros Array :\n", zeros)

#ones array
ones = np.ones((3,3))
print("Ones Array :\n", ones)

#constant array
full = np.full((3,4), 5)
print("FUll or constant array:\n", full)

random= np.random.random((2,3))#creates an array of random value between 0 and 1
print("Random Array:\n", random)


#sequence array: this creates an array
sequence = np.arange(0,11,2)#arange===> array range & (0,11,2)===> (start,stop,jump)
print("Sequence Array:\n", sequence)

Zeros Array :
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones Array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
FUll or constant array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Random Array:
 [[0.46223286 0.80419419 0.9710071 ]
 [0.91270036 0.82296273 0.78723238]]
Sequence Array:
 [ 0  2  4  6  8 10]


## Vector , Matrix , Tensor:

In [51]:
#1D array
vector = np.array([[1,2,3,4,5,6,7,8,9,]])
print("Vector :\n",vector)

#2D array
matrix = np.array([[1,2,3],
                    [4,5,6]])
print("Matrix:\n", matrix)

#tensor : multidimensional array
tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor:\n", tensor)

Vector :
 [[1 2 3 4 5 6 7 8 9]]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
import numpy as np
print(np.__version__)


2.4.6


## array properties

In [53]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6]])

# shape tells you dimension of array
print("Shape:\n", array1.shape)

#dimension :tells you number of array 
print("Dimension:\n", array1.ndim)

#size : total numbers of elements in an array
print("Size:\n", array1.size)

#datatype: tells you a data type which is in majority if not of same data type
print("DataType:\n", array1.dtype)

Shape:
 (2, 3)
Dimension:
 2
Size:
 6
DataType:
 int64


## reshaping in an array 

In [54]:
import numpy as np

array12=np.arange(1,13,2)
print("Original array :\n", array12)

reshaped = array12.reshape((2,3)) #original array into mXn matrix
print("\nReshaped Array:\n", reshaped)

#this creates copy of an array
flatten = reshaped.flatten()
print("\nFlattened Array:\n", flatten)

#this makes changes in original array 
raveled= reshaped.ravel()
print("\n Ravel Array:\n", raveled)

#takes transpose of a matrix
transpose = reshaped.T
print("\nTransposed Array:\n", transpose)

arrr=np.arange(4)
print("\n\n",arrr)

Original array :
 [ 1  3  5  7  9 11]

Reshaped Array:
 [[ 1  3  5]
 [ 7  9 11]]

Flattened Array:
 [ 1  3  5  7  9 11]

 Ravel Array:
 [ 1  3  5  7  9 11]

Transposed Array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]


 [0 1 2 3]
