## manipulations in numpy:

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :", arr[2:7])
print("Jump Index Slicing :", arr[2:5:2])#[start:stop:jump]
print("Negative Slicing :", arr[-3])#len(arr)-3

Basic Slicing : [3 4 5 6 7]
Jump Index Slicing : [3 5]
Negative Slicing : 7


In [8]:
arr_2d=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
print("Specific Element:",arr_2d[1,1])#indexing start from zero for row as well as coloumn
print("Specific Row:", arr_2d[1])#prints the row
print("Specific Coloumn:", arr_2d[:,1])#:===> all the rows and index of coloumn according to the indexing starting from zero

Specific Element: 5
Specific Row: [4 5 6]
Specific Coloumn: [2 5 8]


### Sorting

In [13]:
arra=np.array([9,7,65,44,3,5,777])
print("Sorted Array:", np.sort(arra))

array_2d=np.array([[1,4,3],
                [6,99,4],
                [9,7,8]])
print("\nSorted_2D Array:\n\n", np.sort(array_2d, axis =0))#coloumn operation this sorts the coloumn

print("\nSorted_2D Array:\n\n", np.sort(array_2d, axis =1))#row sorting operation

Sorted Array: [  3   5   7   9  44  65 777]

Sorted_2D Array:

 [[ 1  4  3]
 [ 6  7  4]
 [ 9 99  8]]

Sorted_2D Array:

 [[ 1  3  4]
 [ 4  6 99]
 [ 7  8  9]]


### Filtering:

In [ ]:
num = np.arange(11)
print(num)

filter = num[
    num % 2 == 0
]  # allows you to arrange or get elements by giving expressions
print("Even Numbers : ", filter)

# <========== filter with mask ==============>
mask = num < 8 #this as a hole stores an expressions
print("Numbers less than 8:", num[mask])

[ 0  1  2  3  4  5  6  7  8  9 10]
Even Numbers :  [ 0  2  4  6  8 10]
Numbers less than 8: [0 1 2 3 4 5 6 7]
