## Data Structure :

In [ ]:
import numpy as np
# data of restaurant sales :

data = np.array([
    [1, 1200,1400,4322,4500,4599],#nanskar
    [2, 1144,4585,5265,4852,4585],#pappe
    [3, 7852,4586,9625,4852,3571],#cholewale
    [4, 7864,8569,4500,8035,2345],#dosaram
    [5, 7896,8522,7931,8016,1495],#hub
])

print("shape of array", data.shape)
print("Required Value:\n", data[0:3])
#this means all the row and coloumn starting from index 1 till end
print("Required Value in fancy way:\n", data[:,1:])




shape of array (5, 6)
Required Value:
 [[   1 1200 1400 4322 4500 4599]
 [   2 1144 4585 5265 4852 4585]
 [   3 7852 4586 9625 4852 3571]]
Required Value in fancy way:
 [[1200 1400 4322 4500 4599]
 [1144 4585 5265 4852 4585]
 [7852 4586 9625 4852 3571]
 [7864 8569 4500 8035 2345]
 [7896 8522 7931 8016 1495]]
Sales per year:
 [25956 27662 31643 30255 16595]
Sales Of Each restaurant:
 [16022 20433 30489 31317 33865]
total_sales nanskar  20431


In [ ]:
# <-------------numpy logic------------------->
sales_per_year= np.sum(data[:,1:],axis=0)
print("Sales per year:\n", sales_per_year)


sales_per_year= np.sum(data,axis=1)
print("Sales Of Each restaurant:\n", sales_per_year)

# <------------python logic------------------->
# total sales 
from functools import reduce 
sales_nanskar= data[1,1:]
total_sales= reduce(lambda x,y:x+y,sales_nanskar)
print("total_sales nanskar " , total_sales)


Sales per year:
 [25956 27662 31643 30255 16595]
Sales Of Each restaurant:
 [16022 20433 30489 31317 33865]
total_sales nanskar  20431


## Minimum sales Per Restaurant

In [6]:
# <---------Numpy Logic------------------->

data = np.array([
    [1, 1200,1400,4322,4500,4599],#nanskar
    [2, 1144,4585,5265,4852,4585],#pappe
    [3, 7852,4586,9625,4852,3571],#cholewale
    [4, 7864,8569,4500,8035,2345],#dosaram
    [5, 7896,8522,7931,8016,1495],#hub
])

min_sales_restaurant = np.min(data[:,1:], axis =1)
print(min_sales_restaurant)
#this gives minimum sales per restaurant
# <================same function for max as well ================>>

# <---------Python Logic------------------->
from functools import reduce
min_sales_per_year = data[:, 1]
filtered_sales = reduce(lambda x,y: y if x>y else x, min_sales_per_year)
print("Minimum Sales :",filtered_sales)

[1200 1144 3571 2345 1495]
Minimum Sales : 1144


## Average and Max sales

In [9]:
import numpy as np
from functools import reduce

average_sales_restaurant = np.mean(data[:, 1:], axis=0)
print(average_sales_restaurant)

# reduce can be used as well

# we use max instead of mean and the same function

# cummulative sum
cummulative_sum = np.cumsum(data[:, 1:], axis=1)
print("cummulative Sum :", cummulative_sum)

[5191.2 5532.4 6328.6 6051.  3319. ]
cummulative Sum : [[ 1200  2600  6922 11422 16021]
 [ 1144  5729 10994 15846 20431]
 [ 7852 12438 22063 26915 30486]
 [ 7864 16433 20933 28968 31313]
 [ 7896 16418 24349 32365 33860]]


## Addition multiplication and dot product in numpy 

In [15]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print("Vector Addition :", vector1 + vector2)

print("Vector Multiplication :", vector1 * vector2)

print("Vector Dot Product :", np.dot(vector1,vector2)) 

angle = np.arccos(np.dot(vector1 , vector2)/ (np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(angle)

Vector Addition : [ 7  9 11 13 15]
Vector Multiplication : [ 6 14 24 36 50]
Vector Dot Product : 130
0.26554161733900966
