## manipulations in numpy:


In [ ]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :", arr[2:7])
print("Jump Index Slicing :", arr[2:5:2])#[start:stop:jump]
print("Negative Slicing :", arr[-3])#len(arr)-3

Basic Slicing : [3 4 5 6 7]
Jump Index Slicing : [3 5]
Negative Slicing : 7


In [ ]:
arr_2d=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
print("Specific Element:",arr_2d[1,1])#indexing start from zero for row as well as coloumn
print("Specific Row:", arr_2d[1])#prints the row
print("Specific Coloumn:", arr_2d[:,1])#:===> all the rows and index of coloumn according to the indexing starting from zero

Specific Element: 5
Specific Row: [4 5 6]
Specific Coloumn: [2 5 8]


### Sorting


In [ ]:
arra=np.array([9,7,65,44,3,5,777])
print("Sorted Array:", np.sort(arra))

array_2d=np.array([[1,4,3],
                [6,99,4],
                [9,7,8]])
print("\nSorted_2D Array:\n\n", np.sort(array_2d, axis =0))#coloumn operation this sorts the coloumn

print("\nSorted_2D Array:\n\n", np.sort(array_2d, axis =1))#row sorting operation

Sorted Array: [  3   5   7   9  44  65 777]

Sorted_2D Array:

 [[ 1  4  3]
 [ 6  7  4]
 [ 9 99  8]]

Sorted_2D Array:

 [[ 1  3  4]
 [ 4  6 99]
 [ 7  8  9]]


### Filtering:


In [ ]:
num = np.arange(11)
print(num)

filter = num[
    num % 2 == 0
]  # allows you to arrange or get elements by giving expressions
print("Even Numbers : ", filter)

# <========== filter with mask ==============>
# a short way to write filter 
mask = num < 8 #this as a hole stores an expressions
print("Numbers less than 8:", num[mask])

[ 0  1  2  3  4  5  6  7  8  9 10]
Even Numbers :  [ 0  2  4  6  8 10]
Numbers less than 8: [0 1 2 3 4 5 6 7]


## Fancy Indexing vs np.where()

In [11]:
import numpy as np
# Fancy Indexing : this gives the value of specific index
num1=np.arange(12)
index = [4,5,6,2]
print(num1[index])

#np.where : this works same as mask but it only stores the value if given condition is correct 
#  this on hand stores the index of the the given expression and when viewed this 
# 


where_result = np.where(num1<7)
print("Where Result :", [where_result])
print("Where Result :", num1[where_result])




[4 5 6 2]
Where Result : [(array([0, 1, 2, 3, 4, 5, 6]),)]
Where Result : [0 1 2 3 4 5 6]


## conditional array

In [ ]:
num2 =np.arange(14)
conditional_array = np.where(num2 > 5, num2 * 2, num2)
conditional_array1 = np.where(num2 > 5, "True", "False")
print(conditional_array)
print(conditional_array1)

# this statement behanves as : if num2>5 : print(num*2) else print(num) 

[ 0  1  2  3  4  5 12 14 16 18 20 22 24 26]


## addign and removing data 